        let AIRPORTS = {
            'AAR': 'Aarhus, Denmark',
            'ABD': 'Abadan, Iran',
            'AEH': 'Abeche, Chad',
            'ABZ': 'Aberdeen, United Kingdom',
            'ABR': 'Aberdeen (SD), USA',
            'ABJ': 'Abidjan, Cote d\'Ivoire',
            'ABI': 'Abilene (TX), USA',
            'AUH': 'Abu Dhabi - Abu Dhabi International, United Arab Emirates',
            'AUE': 'Abu Rudels, Egypt',
            'ABS': 'Abu Simbel, Egypt',
            'ABV': 'Abuja - Nnamdi Azikive International Airport, Nigeria',
            'ACA': 'Acapulco, Mexico',
            'ACC': 'Accra - Kotoka International Airport, Ghana',
            'ADA': 'Adana, Turkey',
            'ADD': 'Addis Ababa - Bole International Airport, Ethiopia',
            'ADL': 'Adelaide, Australia',
            'ADE': 'Aden - Aden International Airport, Yemen',
            'ADF': 'Adiyaman, Turkey',
            'AER': 'Adler/Sochi, Russia',
            'AJY': 'Agades, Niger',
            'AGA': 'Agadir, Morocco',
            'SUM': 'Agana (Hagâfîfa), Guam',
            'AGZ': 'Aggeneys, South Africa',
            'BQN': 'Aguadilla, Puerto Rico',
            'AGU': 'Aguascaliente, Mexico',
            'AMD': 'Ahmedabad, India',
            'AYU': 'Aiyura, Papua New Guinea',
            'AJA': 'Ajaccio, France',
            'AXT': 'Akita, Japan',
            'CAK': 'Akron (OH), USA',
            'AKT': 'Akrotiri - RAF, Cyprus',
            'AAN': 'Al Ain, United Arab Emirates',
            'AAC': 'Al Arish, Egypt',
            'AHU': 'Al Hocelma, Morocco',
            'ALH': 'Albany, Australia',
            'ABY': 'Albany (GA), USA',
            'ALB': 'Albany (NY) - Albany International Airport, USA',
            'LBI': 'Albi, France',
            'AAL': 'Alborg, Denmark',
            'ABQ': 'Albuquerque (NM), USA',
            'ABX': 'Albury, Australia',
            'ACI': 'Aldemey, Channel Islands',
            'ALP': 'Aleppo, Syria',
            'AES': 'Alesund, Norway',
            'ELS': 'Alexander Bay - Kortdoorn, South Africa',
            'ESF': 'Alexandria - Esler Field, USA (LA)',
            'HBE': 'Alexandria - Borg el Arab Airport, Egypt',
            'ALY': 'Alexandria - El Nhouza Airport, Egypt',
            'FJR': 'Alfujairah (Fujairah), United Arab Emirates',
            'AHO': 'Alghero Sassari, Italy',
            'ALG': 'Algiers, Houari Boumediene Airport, Algeria',
            'ALC': 'Alicante, Spain',
            'ASP': 'Alice Springs, Australia',
            'ADY': 'Alidays, South Africa',
            'ABE': 'Alientown (PA), USA',
            'ALA': 'Almaty (Alma Ata) - Almaty International Airport, Kazakhstan',
            'LEI': 'Almeria, Spain',
            'ALF': 'Alta, Norway',
            'AAT': 'Altay, PR China',
            'ACH': 'Altenrhein, Switzerland',
            'AOO': 'Altoona (PA), USA',
            'AXS': 'Altus, USA',
            'ASJ': 'Amami, Japan',
            'AMA': 'Amarillo (TX), USA',
            'AZB': 'Amazon Bay, Papua New Guinea',
            'ADJ': 'Amman - Amman-Marka International Airport, Jordan',
            'AMM': 'Amman - Queen Alia International Airport, Jordan',
            'ATQ': 'Amritsar, India',
            'AMS': 'Amsterdam - Amsterdam Airport Schiphol, Netherlands',
            'QNB': 'Anand, India',
            'ANC': 'Anchorage (AK) - Ted Stevens Anchorage International, USA',
            'AOI': 'Ancona - Ancona Falconara Airport, Italy',
            'ALV': 'Andorra La Vella - Heliport, Andorra',
            'AXA': 'Anguilla, Anguilla',
            'AJN': 'Anjouan - Anjouan Airport, Comoros (Comores)',
            'ANK': 'Ankara, Turkey',
            'ESB': 'Ankara - Esenboğa International Airport, Turkey',
            'ARB': 'Ann Arbor (MI), USA',
            'AAE': 'Annaba, Algeria',
            'NCY': 'Annecy, France',
            'ANB': 'Anniston (AL), USA',
            'AYT': 'Antalya, Turkey',
            'TNR': 'Antananarivo (Tanannarive) - Ivato International Airport, Madagascar',
            'ANU': 'Antigua, V.C. Bird International, Antigua and Barbuda',
            'ANR': 'Antwerp, Belgium',
            'AOJ': 'Aomori, Japan',
            'APW': 'Apia - Faleolo International Airport, Samoa',
            'ATW': 'Appelton/Neenah/Menasha (WI), USA',
            'AQJ': 'Aqaba, Jordan',
            'AJU': 'Aracaju, Brazil',
            'GPA': 'Araxos, Greece',
            'ARH': 'Arkhangelsk, Russia',
            'RLT': 'Arlit, Niger',
            'ACE': 'Arrecife/Lanzarote, Spain',
            'AUA': 'Aruba - Reina Beatrix International, Oranjestad, Aruba',
            'ARK': 'Arusha, Tanzania',
            'AVL': 'Asheville (NC), USA',
            'ASB': 'Ashgabat - Saparmurat Turkmenbashy Int. Airport, Turkmenistan',
            'ASM': 'Asmara - Asmara International, Eritrea',
            'ASE': 'Aspen, (CO) - Aspen-Pitkin County Airport, USA',
            'ATZ': 'Assiut, Egypt',
            'TSE': 'Astana - Astana International Airport, Kazakhstan',
            'ASU': 'Asuncion - Asunción International Airport, Paraguay',
            'ASW': 'Aswan, Egypt',
            'ATH': 'Athens - Elefthérios Venizélos International Airport, Greece',
            'AHN': 'Athens (GA), USA',
            'ATO': 'Athens (OH), USA',
            'ATL': 'Atlanta (GA) - Hartsfield Atlanta International Airport, USA',
            'ACY': 'Atlantic City (NJ) - Atlantic City International, USA',
            'AKL': 'Auckland - Auckland International Airport, New Zealand',
            'AGB': 'Augsburg - Augsbur gAirport, Germany',
            'AGS': 'Augusta (GA), USA',
            'AUG': 'Augusta (ME) - Augusta State Airport, USA',
            'AUR': 'Aurillac, France',
            'AUS': 'Austin (TX) - Austin-Bergstrom Airport, USA',
            'AYQ': 'Ayers Rock - Connellan, Australia',
            'AYR': 'Ayr, Australia',
            'BJZ': 'Badajoz, Spain',
            'BGW': 'Baghdad - Baghdad International Airport, Iraq',
            'IXB': 'Bagdogra, India',
            'YBG': 'Bagotville, Canada',
            'BJR': 'Bahar Dar, Ethiopia',
            'BHV': 'Bahawalpur, Pakistan',
            'BAH': 'Bahrain - Bahrain International Airport, Bahrain',
            'BAK': 'Baku - Heydar Aliyev International Airport, Azerbaijan',
            'BNK': 'Ballina, Australia',
            'BWI': 'Baltimore (MD) - Washington International Airport, USA',
            'BKO': 'Bamako - Bamako-Sénou International Airport, Mali',
            'BBY': 'Bambari, Central African Republic',
            'BND': 'Bandar Abbas, Iran',
            'BWN': 'Bandar Seri Begawan - Brunei International Airport, Brunei',
            'BDO': 'Bandung - Husein Sastranegara International Airport, Indonesia',
            'BLR': 'Bangalore - Bengaluru International Airport, India',
            'BKK': 'Bangkok, Suvarnabhumi International, Thailand',
            'BGR': 'Bangor (ME), USA',
            'BGF': 'Bangui - M\'Poko International Airport, Central African Republic',
            'BJL': 'Banjul - Banjul International Airport (Yundum International), Gambia',
            'BNP': 'Bannu, Pakistan',
            'BCN': 'Barcelona, Spain',
            'BLA': 'Barcelona, Venezuela',
            'BDU': 'Bardufoss, Norway',
            'BRI': 'Bari, Italy',
            'BZL': 'Barisal, Bangladesh',
            'BDQ': 'Baroda, India',
            'BRR': 'Barra (the famous tidal beach landing), United Kingdom',
            'BAQ': 'Barranquilla, Colombia',
            'BSL': 'Basel, Switzerland',
            'BSO': 'Basco, Philippines',
            'BIA': 'Bastia, France',
            'BTR': 'Baton Rouge (LA) - Baton Rouge Metropolitan Airport, USA',
            'BYP': 'Bay of Islands, New Zealand',
            'BYU': 'Bayreuth - Bindlacher-Berg, Germany',
            'BPT': 'Beaumont/Pt. Arthur (TX), USA',
            'BKW': 'Beckley (WV), USA',
            'BED': 'Bedford (MA), USA',
            'BEI': 'Beica, Ethiopia',
            'BEY': 'Beirut - Beirut Rafic Hariri International Airport, Lebanon',
            'BEL': 'Belem - Val de Cans International Airport, Brazil',
            'BFS': 'Belfast - Belfast International Airport, United Kingdom',
            'BHD': 'Belfast - George Best Belfast City Airport, United Kingdom',
            'BLG': 'Belaga, Malaysia',
            'BEG': 'Belgrad (Beograd) - Belgrade Nikola Tesla International, Serbia',
            'BZE': 'Belize City - Philip S.W.Goldson International, Belize',
            'BLI': 'Bellingham (WA), USA',
            'CNF': 'Belo Horizonte - Tancredo Neves International Airport, Brazil',
            'BJI': 'Bemidji (MN), USA',
            'BEN': 'Benghazi (Bengasi) - Benina International Airport, Libya',
            'BEH': 'Benton Harbor (MI), USA',
            'BBO': 'Berbera, Somalia',
            'BGY': 'Bergamo/Milan - Orio Al Serio, Italy',
            'BGO': 'Bergen, Norway',
            'EGC': 'Bergerac - Roumanieres, France',
            'BER': 'Berlin, Germany',
            'SXF': 'Berlin, Schoenefeld, Germany',
            'TXL': 'Berlin, Tegel, Germany',
            'THF': 'Berlin, Tempelhof (ceased operating in 2008), Germany',
            'BDA': 'Bermuda - L.F. Wade International Airport, Bermuda',
            'BRN': 'Bern, Switzerland',
            'BET': 'Bethel (AK), USA',
            'BHO': 'Bhopal, India',
            'BBI': 'Bhubaneswar, India',
            'BIK': 'Biak, Indonesia',
            'BIQ': 'Biarritz, France',
            'BIO': 'Bilbao, Spain',
            'BIL': 'Billings (MT), USA',
            'BLL': 'Billund, Denmark',
            'BIM': 'Bimini, Bahamas',
            'NSB': 'Bimini, Bahamas',
            'BTU': 'Bintulu, Malaysia',
            'BIR': 'Biratnagar, Nepal',
            'BVI': 'Birdsville, Australia',
            'BHX': 'Birmingham - Birmingham International Airport, United Kingdom',
            'BHM': 'Birmingham (AL), USA',
            'FRU': 'Bishkek - Manas International Airport, Kyrgyzstan',
            'BIS': 'Bismarck (ND) - Bismarck Municipal Airport, USA',
            'BXO': 'Bissau - Osvaldo Vieiro International Airport, Guinea-Bissau',
            'BLK': 'Blackpool, United Kingdom',
            'BLT': 'Blackwater, Australia',
            'BBK': 'Kasane, Botswana',
            'BLZ': 'Blantyre (Mandala) - Chileka International Airport, Malawi',
            'BHE': 'Blenheim, New Zealand',
            'BFN': 'Bloemfontein - Bloemfontein Airport, South Africa',
            'BMI': 'Bloomington (IL), USA',
            'BMG': 'Bloomington (IN), USA',
            'BLF': 'Bluefield (WV), USA',
            'BVB': 'Boa Vista, Brazil',
            'BOO': 'Bodo, Norway',
            'BOG': 'Bogota - El Nuevo Dorado International Airport, Colombia',
            'BOI': 'Boise (ID) - Boise Air Terminal, USA',
            'BLQ': 'Bologna, Italy',
            'BOM': 'Bombay (Mumbai) - Chhatrapati Shivaji International, India',
            'BON': 'Bonaire, Netherlands Antilles',
            'YVB': 'Bonaventure, Canada',
            'BOB': 'Bora Bora, French Polynesia',
            'BOD': 'Bordeaux - Bordeaux Airport, France',
            'BOS': 'Boston (MA) - Logan International, USA',
            'BYK': 'Bouake, Cote d\'Ivoire',
            'BOJ': 'Bourgas/Burgas, Bulgaria',
            'BZN': 'Bozeman (MT), USA',
            'BFD': 'Bradford/Warren (PA) /Olean (NY), USA',
            'BRD': 'Brainerd (MN), USA',
            'BMP': 'Brampton Island, Australia',
            'BSB': 'Brasilia - President Juscelino Kubitschek International, Brazil',
            'BTS': 'Bratislava - M. R. Štefánik Airport, Slovakia',
            'BZV': 'Brazzaville - Maya-Maya Airport, Congo (ROC)',
            'BRE': 'Bremen, Germany',
            'VBS': 'Brescia, Montichiari, Italy',
            'BES': 'Brest, France',
            'BIV': 'Bria, Central African Republic',
            'BDR': 'Bridgeport (CT), USA',
            'BDS': 'Brindisi, Italy',
            'BNE': 'Brisbane, Australia',
            'BRS': 'Bristol, United Kingdom',
            'BNN': 'Bronnoysund, Norway',
            'BKQ': 'Broken Hill, Australia',
            'BHQ': 'Broken Hill, Australia',
            'BME': 'Broome, Australia',
            'BRO': 'Brownsville (TX), USA',
            'BQK': 'Brunswick (GA), USA',
            'BRU': 'Brussels - Brussels Airport, Belgium',
            'CRL': 'Brussels - Charleroi, Belgium',
            'BGA': 'Bucaramanga, Colombia',
            'BUH': 'Bucharest, Romania',
            'OTP': 'Bucharest - Henri Coandă International Airport, Romania',
            'BUD': 'Budapest - Budapest Ferihegy International Airport, Hungary',
            'BUE': 'Buenos Aires, Argentina',
            'EZE': 'Buenos Aires, Ezeiza International Airport, Argentina',
            'AEP': 'Buenos Aires, Jorge Newbery, Argentina',
            'BFO': 'Buffalo Range, Zimbabwe',
            'BUF': 'Buffalo/Niagara Falls (NY), USA',
            'BJM': 'Bujumbura - Bujumbura International Airport, Burundi',
            'BHK': 'Bukhara, Uzbekistan',
            'BUQ': 'Bulawayo, Zimbabwe',
            'BDB': 'Bundaberg, Australia',
            'BUR': 'Burbank (CA), USA',
            'BRL': 'Burlington (IA), USA',
            'BTV': 'Burlington (VT), USA',
            'BWT': 'Burnie (Wynyard), Australia',
            'BTM': 'Butte (MT), USA',
            'CAG': 'Cagliari, Italy',
            'CNS': 'Cairns, Australia',
            'CAI': 'Cairo - Cairo International Airport, Egypt',
            'CJC': 'Calama - El Loa, Chile',
            'CCU': 'Calcutta (Kolkata) - Netaji Subhas Chandra, India',
            'YYC': 'Calgary - Calgary International Airport, Canada',
            'CLO': 'Cali, Colombia',
            'CCJ': 'Calicut, India',
            'CLY': 'Calvi, France',
            'CBG': 'Cambridge, United Kingdom',
            'YBL': 'Campbell River, Canada',
            'CPE': 'Campeche, Mexico',
            'CGR': 'Campo Grande, Brazil',
            'CBR': 'Canberra - Canberra Airport, Australia',
            'CUN': 'Cancun, Mexico',
            'CEQ': 'Cannes - Mandelieu Airport, France',
            'CIW': 'Canouan (island) - Canouan Airport, Saint Vincent & the Grenadines',
            'CPT': 'Cape Town - Cape Town International Airport, South Africa',
            'CCS': 'Caracas - Simón Bolívar International Airport, Venezuela',
            'CWL': 'Cardiff - Cardiff Airport, United Kingdom',
            'CLD': 'Carlsbad (CA), USA',
            'CNM': 'Carlsbad (NM), USA',
            'CTG': 'Cartagena - Rafael Núñez International Airport, Colombia',
            'CMN': 'Casablanca - Mohamed V, Morocco',
            'CAS': 'Casablanca, Anfa, Morocco',
            'CPR': 'Casper (WY), USA',
            'CST': 'Castaway, Fiji',
            'CTA': 'Catania, Italy',
            'CAY': 'Cayenne - Cayenne-Rochambeau Airport, French Guiana',
            'CEB': 'Cebu - Mactan-Cebu International, Philippines',
            'CDC': 'Cedar City (UT), USA',
            'CID': 'Cedar Rapids (IA), USA',
            'CED': 'Ceduna, Australia',
            'CES': 'Cessnock, Australia',
            'KHV': 'Chabarovsk (Khabarovsk), Russia',
            'CMF': 'Chambery, France',
            'CMI': 'Champaign (IL), USA',
            'IXC': 'Chandigarh, India',
            'CHG': 'Chaoyang, China',
            'CHQ': 'Chania, Greece',
            'CHS': 'Charleston (SC), USA',
            'CRW': 'Charleston (WV) - Yeager Airport, USA',
            'CLT': 'Charlotte (NC), USA',
            'CHO': 'Charlottesville (VA), USA',
            'CHA': 'Chattanooga (TN), USA',
            'CYS': 'Cheyenne (WY) - Cheyenne Regional Airport, USA',
            'CNX': 'Chiang Mai - Chiang Mai International Airport, Thailand',
            'CEI': 'Chiang Rai, Thailand',
            'YMT': 'Chibougamau, Canada',
            'CHI': 'Chicago (IL), USA',
            'MDW': 'Chicago (IL), Midway, USA',
            'ORD': 'Chicago (IL), O\'Hare International Airport, USA',
            'CZA': 'Chichen Itza, Mexico',
            'CHI': 'Chico (CA), USA',
            'CUU': 'Chihuahua, Gen Fierro Villalobos, Mexico',
            'JKH': 'Chios, Greece',
            'CIP': 'Chipata, Zambia',
            'KIV': 'Chisinau - Chișinău International Airport, Moldova',
            'HTA': 'Chita (Tschita), Russia',
            'HMI': 'Hami, China',
            'CJL': 'Chitral, Pakistan',
            'CGP': 'Chittagong, Bangladesh',
            'CHC': 'Christchurch, New Zealand',
            'STX': 'Christiansted, Virgin Islands (U.S.)',
            'CCZ': 'Chub Cay, Bahamas',
            'CVG': 'Cincinnati (OH) - Cincinnati/Northern Kentucky Int\'l, USA',
            'CME': 'Ciudad Del Carmen, Mexico',
            'CEN': 'Ciudad Obregon, Mexico',
            'CJS': 'Ciudad Juarez - Intl. Abraham Gonzalez, Mexico',
            'CVM': 'Ciudad Victoria, Mexico',
            'CFE': 'Clermont Ferrand, France',
            'CLE': 'Cleveland (OH) - Cleveland Hopkins International, USA',
            'CVN': 'Clovis (NM), USA',
            'CLJ': 'Cluj, Romania',
            'YCY': 'Clyde River, Canada',
            'CBB': 'Cochabamba, Bolivia',
            'COK': 'Cochin, India',
            'COD': 'Cody/Powell/Yellowstone (WY), USA',
            'CFA': 'Coffee Point (AK), USA',
            'CFS': 'Coffs Harbour, Australia',
            'CJB': 'Coimbatore, India',
            'CLQ': 'Colima, Mexico',
            'CLL': 'College Station/Bryan (TX), USA',
            'CGN': 'Cologne - Cologne Airport (Flughafen Köln/Bonn), Germany',
            'CMB': 'Colombo - Bandaranaike International Airport, Sri Lanka',
            'COS': 'Colorado Springs (CO), USA',
            'CAE': 'Columbia (SC) - Columbia Metropolitan Airport, USA',
            'CSG': 'Columbus (GA), USA',
            'CMH': 'Columbus (OH) - Port Columbus International, USA',
            'CCU': 'Columbus (OH) - Columbus International Airport, USA',
            'CBM': 'Columbus (MS) - Columbus AFB, USA',
            'CYR': 'Colonia, Uruguay',
            'CPH': 'Copenhagen - Copenhagen Airport, Denmark',
            'CPO': 'Copiapo, Chile',
            'COR': 'Cordoba, Argentina',
            'ODB': 'Cordoba, Spain',
            'CFU': 'Corfu, Greece',
            'ORK': 'Cork, Ireland',
            'CRP': 'Corpus Christi (TX), USA',
            'CZE': 'Coro, Venezuela',
            'CGA': 'Craig (AK), USA',
            'CEC': 'Crescent City (CA), USA',
            'CGB': 'Cuiaba - Marechal Rondon International Airport, Brazil',
            'CUL': 'Culiacan, Mexico',
            'CUR': 'Curacao - Curaçao International Airport, Netherlands Antilles',
            'CWB': 'Curitiba - Afonso Pena International Airport, Brazil',
            'CUZ': 'Cuzco - Velazco Astete, Peru',
            'DAD': 'Da Nang, Vietnam',
            'DKR': 'Dakar - Léopold Sédar Senghor International Airport, Senegal',
            'DLM': 'Dalaman, Turkey',
            'DLZ': 'Dalanzadgad, Mongolia',
            'DLC': 'Dalian - Zhoushuizi International Airport, China',
            'DAL': 'Dallas (TX) , Love Field, USA',
            'DFW': 'Dallas/Fort Worth (TX) - Dallas/Fort Worth International, USA',
            'DAM': 'Damascus, International, Syria',
            'DMM': 'Dammam, King Fahad International, Saudi Arabien',
            'DAN': 'Danville (VA), USA',
            'DAR': 'Dar es Salam (Daressalam) - Julius Nyerere International, Tanzania',
            'DRW': 'Darwin, Australia',
            'DAI': 'Darjeeling, India',
            'DVO': 'Davao - Francisco Bangoy International, Philippines',
            'DWD': 'Dawadmi, Saudi Arabia',
            'DAY': 'Dayton (OH), USA',
            'DAB': 'Daytona Beach (FL), USA',
            'DEC': 'Decatur (IL), USA',
            'DEL': 'Delhi - Indira Gandhi International Airport, India',
            'DPS': 'Denpasar/Bali, Indonesia',
            'DEN': 'Denver (CO) - Denver International Airport, USA',
            'DSK': 'Dera Ismail Khan, Pakistan',
            'DRB': 'Derby, Australia',
            'DER': 'Derim, Papua New Guinea',
            'DSM': 'Des Moines (IA) - Des Moines International Airport, USA',
            'DET': 'Detroit (MI) , Coleman A. Young Municipal, USA',
            'DTW': 'Detroit (MI) - Wayne County Metropolitan Airport, USA',
            'DTT': 'Detroit (MI) , Metropolitan Area, USA',
            'DVL': 'Devils Lake (ND), USA',
            'DHA': 'Dhahran, Saudi Arabia',
            'DAC': 'Dhaka - Zia International Airport, Bangladesh',
            'DIL': 'Dili - Nicolau Lobato International Airport, East Timor (Timor-Leste)',
            'DLG': 'Dillingham (AK), USA',
            'DNR': 'Dinard, France',
            'DPL': 'Dipolog, Philippines',
            'DIG': 'Diqing, China',
            'DIU': 'Diu, India',
            'DIJ': 'Dijon, France',
            'DJE': 'Djerba, Tunisia',
            'JIB': 'Djibouti (city) - Djibouti-Ambouli International Airport, Djibouti',
            'DOD': 'Dodoma - Dodoma Airport, Tanzania',
            'DOH': 'Doha - Doha International Airport, Qatar',
            'DCF': 'Dominica - Cane Field, Dominica',
            'DOM': 'Dominica - Melville Hall, Dominica',
            'DSA': 'Doncaster/Sheffield, Robin Hood Airport, United Kingdom',
            'DOK': 'Donetsk, Donetsk International Airport, Ukraine',
            'DTM': 'Dortmund, Germany',
            'DHN': 'Dothan (AL), USA',
            'DLA': 'Douala, Cameroon',
            'DRS': 'Dresden - Dresden Airport, Germany',
            'XNB': 'Dubai - Bus Station, United Arab Emirates',
            'DXB': 'Dubai - International, United Arab Emirates',
            'DBO': 'Dubbo, Australia',
            'DUB': 'Dublin - Dublin International Airport, Ireland',
            'DBV': 'Dubrovnik, Croatia (Hrvatska)',
            'DBQ': 'Dubuque IA, USA',
            'DUJ': 'Du Bois (PA), USA',
            'DLH': 'Duluth (MN) / Superior (WI), USA',
            'DND': 'Dundee, United Kingdom',
            'DUD': 'Dunedin, New Zealand',
            'DRO': 'Durango (CO), USA',
            'DUR': 'Durban - King Shaka International, South Africa',
            'DYU': 'Dushanbe (Duschanbe) - Dushanbe Airport, Tajikistan',
            'DUS': 'Düsseldorf - Düsseldorf International Airport, Germany',
            'DUT': 'Dutch Harbor (AK), USA',
            'DYA': 'Dysart, Australia',
            'DZA': 'Dzaoudzi, Mayotte',
            'ELS': 'East London, South Africa',
            'EDI': 'Edinburgh - Edinburgh Airport, Scotland, UK',
            'YEA': 'Edmonton, Canada',
            'YEG': 'Edmonton, International, Canada',
            'YXD': 'Edmonton, Municipal, Canada',
            'EGS': 'Egilsstadir, Iceland',
            'EIN': 'Eindhoven, Netherlands',
            'EBA': 'Elba Island, Italy',
            'ETH': 'Elat, Israel',
            'VDA': 'Elat, Ovula, Israel',
            'EKI': 'Elkhart (IN), USA',
            'EKO': 'Elko (NV), USA',
            'ELM': 'Elmira (NY), USA',
            'ELP': 'El Paso (TX) - El Paso International Airport, USA',
            'EMD': 'Emerald, Australia',
            'ENF': 'Enontekioe, Finland',
            'ENS': 'Enschede, Netherlands',
            'EBB': 'Entebbe - Entebbe International Airport, Uganda',
            'ERF': 'Erfurt - Erfurt Airport (Flughafen Erfurt), Germany',
            'ERI': 'Erie (PA), USA',
            'EVN': 'Erevan - Yerevan-Zvartnots, Armenia',
            'ERC': 'Erzincan, Turkey',
            'ERZ': 'Erzurum, Turkey',
            'EBJ': 'Esbjerg, Denmark',
            'ESC': 'Escanaba (MI), USA',
            'EUG': 'Eugene (OR), USA',
            'ACV': 'Eureka (CA), USA',
            'EVV': 'Evansville (IN), USA',
            'EXT': 'Exeter, United Kingdom',
            'FAI': 'Fairbanks (AK), USA',
            'FAR': 'Fargo (ND), USA',
            'FMN': 'Farmington (NM), USA',
            'FAO': 'Faro, Portugal',
            'FAY': 'Fayetteville/Ft. Bragg (NC), USA',
            'FEN': 'Fernando de Noronha, Brazil',
            'FEZ': 'Fes, Morocco',
            'FSC': 'Figari, France',
            'FLG': 'Flagstaff (AZ), USA',
            'FNT': 'Flint (MI), USA',
            'FLR': 'Florence (Firenze) - Peretola Airport, Italy',
            'FLO': 'Florence (SC), USA',
            'FLN': 'Florianopolis, Brazil',
            'FRO': 'Floro, Norway',
            'FDE': 'Forde, Norway',
            'FRA': 'Frankfurt/Main - Frankfurt Airport (Rhein-Main-Flughafen), Germany',
            'HHN': 'Frankfurt/Hahn, Germany',
            'FKL': 'Franklin/Oil City (PA), USA',
            'FNA': 'Freetown - Freetown-Lungi International Airport, Sierra Leone',
            'FRJ': 'Fréjus, France',
            'FAT': 'Fresno (CA), USA',
            'FDH': 'Friedrichshafen - Bodensee-Airport Friedrichshafen, Germany',
            'FUE': 'Fuerteventura, Spain',
            'FUK': 'Fukuoka, Japan',
            'FKS': 'Fukushima - Fukushima Airport, Japan',
            'FNC': 'Funchal, Portugal',
            'FUT': 'Futuna, Wallis and Futuna Islands',
            'GBE': 'Gaborone - Sir Seretse Khama International Airport, Botswana',
            'GAD': 'Gadsden (AL), USA',
            'GNV': 'Gainesville (FL), USA',
            'GWY': 'Galway, Ireland',
            'GUP': 'Gallup (NM), USA',
            'GMB': 'Gambela, Ethiopia',
            'GAN': 'Gan Island, Maldives',
            'GCK': 'Garden City (KS), USA',
            'GOU': 'Garoua, Cameroon',
            'GZT': 'Gaziantep, Turkey',
            'GDN': 'Gdansk, Poland',
            'GEX': 'Geelong, Australia',
            'GVA': 'Geneva - Geneva-Cointrin International Airport, Switzerland',
            'GOA': 'Genoa, Italy',
            'GRJ': 'George, South Africa',
            'GEO': 'Georgetown - Cheddi Jagan International Airport, Guyana',
            'GET': 'Geraldton, Australia',
            'GRO': 'Gerona, Spain',
            'LTD': 'Ghadames, Libya',
            'GHA': 'Ghardala, Algeria',
            'GIB': 'Gibraltar, Gibraltar',
            'GIL': 'Gilgit, Pakistan',
            'GCC': 'Gillette (WY), USA',
            'GLA': 'Glasgow, Scotland, UK',
            'PIK': 'Glasgow, Prestwick, Scotland, UK',
            'GLT': 'Gladstone, Australia',
            'GGW': 'Glasgow (MT), USA',
            'GDV': 'Glendive (MT), USA',
            'GOI': 'Goa, India',
            'GYN': 'Goiania, Santa Genoveva Airport, Brazil',
            'GOB': 'Goba, Ethiopia',
            'GDE': 'Gode/Iddidole, Ethiopia',
            'YGO': 'Gods Lake Narrows, Canada',
            'GDL': 'Guadalajara, Mexico',
            'GOM': 'Goma, Congo (DRC)',
            'GOV': 'Gove (Nhulunbuy), Australia',
            'GHB': 'Governor\'s Harbour, Bahamas',
            'GRX': 'Granada, Spain',
            'GCN': 'Grand Canyon (AZ), USA',
            'GFK': 'Grand Forks (ND), USA',
            'GJT': 'Grand Junction (CO), USA',
            'GRR': 'Grand Rapids (MI), USA',
            'GCM': 'Grand Cayman - Owen Roberts International, Cayman Islands',
            'GND': 'Grenada - Point Salines Airport also Maurice Bishop, Grenada',
            'GNB': 'Grenoble, France',
            'GFF': 'Griffith, Australia',
            'GRZ': 'Graz, Austria',
            'GDT': 'Guantanamo, Cuba',
            'GUA': 'Guatemala City - La Aurora International Airport, Guatemala',
            'GYE': 'Guayaquil - Simon Bolivar, Ecuador',
            'GCI': 'Guernsey, Channel Islands',
            'GTI': 'Guettin, Germany',
            'GPT': 'Gulfport/Biloxi (MS), USA',
            'GUC': 'Gunnison/Crested Butte (CO), USA',
            'KWL': 'Guilin - Liangjiang, China',
            'ULU': 'Gulu, Uganda',
            'GUM': 'Guam, Guam',
            'GUR': 'Alotau, Papua New Guinea',
            'GWD': 'Gwadar, Pakistan',
            'GWE': 'Gweru, Zimbabwe',
            'GYP': 'Gympie, Australia',
            'HAC': 'Hachijo Jima, Japan',
            'HGR': 'Hagerstown (MD), USA',
            'HFA': 'Haifa, Israel',
            'HNS': 'Haines (AK), USA',
            'HKD': 'Hakodate, Japan',
            'YHZ': 'Halifax International, Canada',
            'HAM': 'Hamburg - Hamburg Airport, Germany',
            'HLT': 'Hamilton, Australia',
            'HTI': 'Hamilton Island, Australia',
            'HLZ': 'Hamilton, New Zealand',
            'YHM': 'Hamilton, Canada',
            'HFT': 'Hammerfest, Norway',
            'CMX': 'Hancock (MI), USA',
            'HGH': 'Hangzhou, China',
            'HAJ': 'Hannover, Germany',
            'HAN': 'Hanoi - Noi Bai International Airport, Vietnam',
            'HRE': 'Harare - Harare International Airport, Zimbabwe',
            'HRB': 'Harbin (Haerbin), China',
            'HRL': 'Harlingen/South Padre Island (TX), USA',
            'MDT': 'Harrisburg (PA) - Harrisburg International, USA',
            'HRO': 'Harrison (AR), USA',
            'BDL': 'Hartford (CT) /Springfield (MA), USA',
            'HDY': 'Hat Yai, Thailand',
            'HAU': 'Haugesund, Norway',
            'HAV': 'Havana - José Martí International, Cuba',
            'HVR': 'Havre (MT), USA',
            'HIS': 'Hayman Island, Australia',
            'HLN': 'Helena (MT), USA',
            'JHE': 'Helsingborg, Sweden',
            'HEL': 'Helsinki - Vantaa, Finland',
            'HER': 'Heraklion, Greece',
            'HMO': 'Hermosillo - Gen. Pesqueira Garcia, Mexico',
            'HVB': 'Hervey Bay, Australia',
            'HIB': 'Hibbing (MN), USA',
            'HKY': 'Hickory (NC), USA',
            'ITO': 'Hilo (HI), USA',
            'HHH': 'Hilton Head Island (SC), USA',
            'HIJ': 'Hiroshima International, Japan',
            'SGN': 'Ho Chi Minh City (Saigon) - Tan Son Nhat International, Vietnam',
            'HBA': 'Hobart, Australia',
            'HOB': 'Hobbs (NM), USA',
            'HDS': 'Hoedspruit, South Africa',
            'HOQ': 'Hof, Germany',
            'HOF': 'Hofuf, Saudi Arabia',
            'HOG': 'Holguin, Cuba',
            'HOM': 'Homer (AK), USA',
            'HKG': 'Hong Kong - International Airport (HKIA), Hong Kong',
            'HIR': 'Honiara Henderson International, Solomon Islands',
            'HNL': 'Honolulu (HI) - Honolulu International Airport, USA',
            'HOR': 'Horta, Portugal',
            'HOU': 'Houston (TX) , Hobby, USA',
            'IAH': 'Houston (TX) , George Bush Intercontinental Airport, USA',
            'HUH': 'Huahine, French Polynesia',
            'HUX': 'Huatulco, Mexico',
            'HUI': 'Hue, Vietnam',
            'HUY': 'Humberside, United Kingdom',
            'HTS': 'Huntington (WV), USA',
            'HSV': 'Huntsville (AL), USA',
            'HRG': 'Hurghada International, Egypt',
            'HON': 'Huron (SD), USA',
            'HYN': 'Huangyan, China',
            'HYA': 'Hyannis (MA), USA',
            'HYD': 'Hyderabad - Rajiv Gandhi International Airport, India',
            'IBZ': 'Ibiza, Ibiza/Es Codola, Spain',
            'IDA': 'Idaho Falls (ID), USA',
            'IGR': 'Iguazu, Cataratas, Argentina',
            'ILP': 'Ile des Pins, New Caledonia',
            'IOS': 'Ilheus, Brazil',
            'ILI': 'Iliamna (AK), USA',
            'IPL': 'Imperial (CA), USA',
            'IND': 'Indianapolis (IN) International, USA',
            'INN': 'Innsbruck, Austria',
            'INL': 'International Falls (MN), USA',
            'IVC': 'Invercargill, New Zealand',
            'INV': 'Inverness, United Kingdom',
            'IYK': 'Inykern (CA), USA',
            'IOA': 'Ioannina, Greece',
            'IPH': 'Ipoh, Malaysia',
            'YFB': 'Iqaluit (Frobisher Bay), Canada',
            'IQQ': 'Iquique - Cavancha, Chile',
            'IQT': 'Iquitos, Peru',
            'ISG': 'Ishigaki, Japan',
            'ISB': 'Islamabad - Benazir Bhutto International Airport, Pakistan',
            'IST': 'Istanbul - Istanbul Atatürk Airport, Turkey',
            'SAW': 'Istanbul - Sabiha Gokcen, Turkey',
            'ITH': 'Ithaca/Cortland (NY), USA',
            'IVL': 'Ivalo, Finland',
            'IWJ': 'Iwami, Japan',
            'ZIH': 'Ixtapa/Zihuatanejo, Mexico',
            'IZM': 'Izmir, Turkey',
            'JAC': 'Jackson Hole (WY), USA',
            'JAN': 'Jackson (MS) - Jackson Internationall, USA',
            'MKL': 'Jackson (TN) - Mckellar, USA',
            'JAX': 'Jacksonville (FL) - International, USA',
            'JAI': 'Jaipur - Sanganeer, India',
            'JAL': 'Jalapa, Mexico',
            'JMS': 'Jamestown (ND), USA',
            'JHW': 'Jamestown (NY), USA',
            'JED': 'Jeddah - King Abdulaziz International, Saudi Arabia',
            'JEF': 'Jefferson City (MO) - Jefferson Memorial, USA',
            'JER': 'Jersey, Channel Islands',
            'JSR': 'Jessore - Jessore Airport, Bangladesh',
            'JHB': 'Johor Bahru - Sultan Ismail International, Malaysia',
            'JNB': 'Johannesburg - OR Tambo International Airport, South Africa',
            'JST': 'Johnstown (PA), USA',
            'JNB': 'Johannesburg - OR Tambo International Airport, South Africa',
            'JSM': 'Jose de San Martin, Argentina',
            'AJF': 'Jouf, Saudi Arabia',
            'JDO': 'Juazeiro do Norte, Brazil',
            'JUJ': 'Jujuy - El Cadillal Airport, Argentina',
            'JCK': 'Julia Creek, Australia',
            'JUL': 'Juliaca, Peru',
            'JNU': 'Juneau (AK) - Juneau International Airport, USA',
            'JUT': 'Juticalpa, Honduras',
            'KIX': 'Kansai, Osaka, Japan',
            'KGI': 'Kalgoorlie, Australia',
            'KLO': 'Kalibo, Philippines',
            'KGD': 'Kaliningrad, Russia',
            'FCA': 'Kalispell (MT), USA',
            'KLR': 'Kalmar, Sweden',
            'YKA': 'Kamloops, Canada',
            'MUE': 'Kamuela (HI), USA',
            'KAN': 'Kano, Nigeria',
            'MCI': 'Kansas City (MO) - Kansas City International Airport, USA',
            'JHM': 'Kapalua West (HI), USA',
            'KHI': 'Karachi - Jinnah International Airport, Pakistan',
            'FKB': 'Karlsruhe-Baden - Soellingen, Germany',
            'KSD': 'Karlstad, Sweden',
            'AOK': 'Karpathos, Greece',
            'KTA': 'Karratha, Australia',
            'KNU': 'Kanpur, India',
            'KRP': 'Karup, Denmark',
            'ZKE': 'Kaschechewan, Canada',
            'KSL': 'Kassala, Sudan',
            'KTR': 'Katherine, Australia',
            'KTW': 'Katowice, Poland',
            'LIH': 'Kauai Island (HI), USA',
            'KVA': 'Kavalla, Greece',
            'ASR': 'Kayseri, Turkey',
            'KZN': 'Kazan - Kazan International Airport, Russia',
            'EAR': 'Kearney (NE), USA',
            'KEL': 'Kiel - Holtenau, Germany',
            'KGL': 'Kigali - Gregoire Kayibanda, Rwanda',
            'JRO': 'Kilimanjaro, Tanzania',
            'ILE': 'Killeem (TX), USA',
            'KIM': 'Kimberley, South Africa',
            'KIN': 'Kingston - Norman Manley, Jamaica',
            'KIN': 'Kingston - Tinson, Jamaica',
            'KTP': 'Kingston - Tinson, Jamaica',
            'FIH': 'Kinshasa - N\'Djili, Congo (DRC)',
            'ISO': 'Kinston (NC), USA',
            'KIR': 'Kerry County, Ireland',
            'KKN': 'Kirkenes, Norway',
            'KOI': 'Kirkwall, Orkney Islands, UK',
            'KRN': 'Kiruna, Sweden',
            'KIS': 'Kisumu, Kenya',
            'KTT': 'Kittilä, Finland',
            'KLU': 'Klagenfurt, Austria',
            'LMT': 'Klamath Falls (OR), USA',
            'KLW': 'Klawock (AK), USA',
            'TYS': 'Knoxville (TN), USA',
            'UKB': 'Kobe, Japan',
            'KCZ': 'Kochi, Japan',
            'ADQ': 'Kodiak (AK), USA',
            'KOJ': 'Kagoshima, Japan',
            'KOK': 'Kokkola/Pietarsaari, Finland',
            'KMQ': 'Komatsu, Japan',
            'KOA': 'Kona (HI), USA',
            'KYA': 'Konya, Turkey',
            'KRL': 'Korla, China',
            'KGS': 'Kos, Greece',
            'BKI': 'Kota Kinabalu, Malaysia',
            'KBV': 'Krabi, Thailand',
            'KRK': 'Krakow (Cracow) - John Paul II International Airport, Poland',
            'KRF': 'Kramfors, Sweden',
            'KRS': 'Kristiansand, Norway',
            'KID': 'Kristianstad, Sweden',
            'KSU': 'Kristiansund, Norway',
            'KUL': 'Kuala Lumpur - International Airport, Malaysia',
            'SZB': 'Kuala Lumpur - Sultan Abdul Aziz Shah, Malaysia',
            'KUA': 'Kuantan, Malaysia',
            'KCH': 'Kuching, Malaysia',
            'KMJ': 'Kumamoto, Japan',
            'KNX': 'Kununurra, Australia',
            'KUO': 'Kuopio, Finland',
            'KUH': 'Kushiro, Japan',
            'YGW': 'Kuujjuarapik, Canada',
            'KAJ': 'Kajaani, Finland',
            'KWI': 'Kuwait - Kuwait International, Kuwait',
            'KYZ': 'Kyzyl, Russia',
            'LCE': 'La Ceiba, Honduras',
            'LCG': 'La Coruna, Spain',
            'LSE': 'La Crosse (WI), USA',
            'LAF': 'Lafayette (IN), USA',
            'LFT': 'Lafayette, La, USA',
            'LCH': 'Lake Charles (LA), USA',
            'LNY': 'Lanai City (HI), USA',
            'LNS': 'Lancaster (PA), USA',
            'LGK': 'Langkawi (islands), Malaysia',
            'LAI': 'Lannion, France',
            'LAN': 'Lansing (MI), USA',
            'LAP': 'La Paz - Leon, Mexico',
            'LPB': 'La Paz - El Alto, Bolivia',
            'LPP': 'Lappeenranta, Finland',
            'LAR': 'Laramie (WY), USA',
            'LRD': 'Laredo (TX), USA',
            'LCA': 'Larnaca, Cyprus',
            'LRH': 'La Rochelle, France',
            'LPA': 'Las Palmas, Spain',
            'LAS': 'Las Vegas (NV), USA',
            'LBE': 'Latrobe (PA), USA',
            'LST': 'Launceston, Australia',
            'PIB': 'Laurel/Hattisburg (MS), USA',
            'LAW': 'Lawton (OK), USA',
            'LZC': 'Lazaro Cardenas, Mexico',
            'YGL': 'La Grande, Canada',
            'LEH': 'Le Havre, France',
            'LEA': 'Learmouth (Exmouth), Australia',
            'LEB': 'Lebanon (NH), USA',
            'LBA': 'Leeds/Bradford, UK',
            'LGP': 'Legaspi, Philippines',
            'LEI': 'Almeria, Spain',
            'LEJ': 'Leipzig, Germany',
            'LEN': 'Leon, Spain',
            'LWO': 'Lviv, Ukraine',
            'LWS': 'Lewiston (ID), USA',
            'LWT': 'Lewistown (MT), USA',
            'LEX': 'Lexington (KY), USA',
            'LXA': 'Lhasa, China',
            'LXR': 'Luxor, Egypt',
            'LHW': 'Lanzhou, China',
            'LYG': 'Lianyungang, China',
            'LIR': 'Liberia, Costa Rica',
            'LBV': 'Libreville, Gabon',
            'LGG': 'Liege, Belgium',
            'LIF': 'Lifou, New Caledonia',
            'LIG': 'Limoges, France',
            'LNK': 'Lincoln (NE), USA',
            'LDC': 'Lindeman Island, Australia',
            'LDI': 'Lindi, Tanzania',
            'LPI': 'Linkoping, Sweden',
            'LNJ': 'Lincang, China',
            'LIS': 'Lisbon - Lisboa, Portugal',
            'LSY': 'Lismore, Australia',
            'LIT': 'Little Rock (AR), USA',
            'LPL': 'Liverpool, UK',
            'LIV': 'Livingstone, Zambia',
            'LJU': 'Ljubljana - Brnik, Slovenia',
            'IRG': 'Lockhart River, Australia',
            'LFW': 'Lome, Togo',
            'LGB': 'Long Beach (CA), USA',
            'LIJ': 'Long Island (AK), USA',
            'HAP': 'Long Island, Australia',
            'LRE': 'Longreach, Australia',
            'LDW': 'Lansdowne, Australia',
            'LTO': 'Loreto, Mexico',
            'LRT': 'Lorient, France',
            'LAX': 'Los Angeles (CA) - International, USA',
            'SDF': 'Louisville (KY), USA',
            'LDE': 'Lourdes/Tarbes, France',
            'LAD': 'Luanda - 4 de Fevereiro, Angola',
            'LBB': 'Lubbock (TX), USA',
            'LKO': 'Lucknow, India',
            'LUD': 'Luederitz, Namibia',
            'LUG': 'Lugano, Switzerland',
            'LLA': 'Lulea, Sweden',
            'FBM': 'Lumbumbashi, Congo (DRC)',
            'LUN': 'Lusaka - Lusaka International Airport, Zambia',
            'LUW': 'Luwuk, Indonesia',
            'LUX': 'Luxembourg, Luxembourg',
            'LUM': 'Luxi - Mangshi, China',
            'LXR': 'Luxor, Egypt',
            'LWO': 'Lviv, Ukraine',
            'LYA': 'Luoyang, China',
            'LYH': 'Lynchburg (VA), USA',
            'LYS': 'Lyon - Lyon-Saint Exupéry Airport, France',
            'MST': 'Maastricht/Aachen, Netherlands',
            'MCP': 'Macapa, Brazil',
            'MFM': 'Macau - Macau International Airport, Macau',
            'MCZ': 'Maceio - Zumbi dos Palmares International, Brazil',
            'MKY': 'Mackay, Australia',
            'MCN': 'Macon (GA), USA',
            'MED': 'Madinah (Medina) - Mohammad Bin Abdulaziz, Saudi Arabia',
            'MSN': 'Madison (WI) - Dane County Regional Airport, USA',
            'MAA': 'Madras (Chennai) - Chennai International Airport, India',
            'MAD': 'Madrid - Barajas Airport, Spain',
            'SEZ': 'Mahe - Seychelles International, Seychelles',
            'MAH': 'Mahon, Spain',
            'MTL': 'Maitland, Australia',
            'MJG': 'Mayajigua, Cuba',
            'MJN': 'Majunga, Madagascar',
            'MCI': 'Kansas City (MO) - Kansas City International Airport, USA',
            'MKY': 'Mackay, Australia',
            'AKP': 'Anaktuvuk (AK), USA',
            'MLE': 'Male - International Airport, Maldives',
            'MYD': 'Malindi, Kenya',
            'MMA': 'Malmo (Malmoe), Sweden',
            'MMX': 'Malmo (Malmö) - Malmö Airport, Sweden',
            'MNC': 'Nacala, Mozambique',
            'MGA': 'Managua - Augusto C Sandino, Nicaragua',
            'MAO': 'Manaus - Eduardo Gomes International, Brazil',
            'MAN': 'Manchester, UK',
            'MHT': 'Manchester (NH), USA',
            'MFE': 'McAllen (TX), USA',
            'MHK': 'Manhattan (KS), USA',
            'MNL': 'Manila - Ninoy Aquino International, Philippines',
            'ZLO': 'Manzanillo, Mexico',
            'MTS': 'Manzini - Matsapha International, Eswatini',
            'MPM': 'Maputo - Maputo International, Mozambique',
            'MDQ': 'Mar del Plata, Argentina',
            'MAR': 'Maracaibo - La Chinita, Venezuela',
            'RMF': 'Marsa Alam, Egypt',
            'MQM': 'Mardin, Turkey',
            'MEE': 'Mare, New Caledonia',
            'MGH': 'Margate, South Africa',
            'PMV': 'Margerita, Venezuela',
            'MBX': 'Maribor, Slovenia',
            'MHQ': 'Mariehamn (Maarianhamina), Finland',
            'MVR': 'Maroua, Cameroon',
            'MQT': 'Marquette (MI), USA',
            'RAK': 'Marrakesh - Menara, Morocco',
            'RMF': 'Marsa Alam, Egypt',
            'MRS': 'Marseille, France',
            'MHH': 'Marsh Harbour, Bahamas',
            'MVY': 'Martha\'s Vineyard (MA), USA',
            'MRU': 'Mauritius - S.Seewoosagur Ram International, Mauritius',
            'MAZ': 'Mayaguez, Puerto Rico',
            'MZT': 'Mazatlan, Mexico',
            'MFE': 'McAllen (TX), USA',
            'MCW': 'Mason City (IA), USA',
            'MES': 'Medan - Polania, Indonesia',
            'MED': 'Madinah (Medina) - Mohammad Bin Abdulaziz, Saudi Arabia',
            'MEH': 'Mehamn, Norway',
            'MXZ': 'Meixian, China',
            'MYU': 'Mekoryuk (AK), USA',
            'MLB': 'Melbourne (FL), USA',
            'MEL': 'Melbourne - Tullamarine, Australia',
            'MLN': 'Melilla, Spain',
            'MEM': 'Memphis (TN), USA',
            'MDZ': 'Mendoza, Argentina',
            'MCE': 'Merced (CA), USA',
            'MID': 'Merida, Mexico',
            'MEI': 'Meridian (MS), USA',
            'MIM': 'Merimbula, Australia',
            'MTY': 'Monterrey - Gen. Mariano Escobedo, Mexico',
            'MEX': 'Mexico City - Mexico City International Airport, Mexico',
            'MIA': 'Miami (FL), USA',
            'MAF': 'Midland/Odessa (TX), USA',
            'MIL': 'Milan, Italy',
            'MXP': 'Milan - Malpensa, Italy',
            'LIN': 'Milan - Linate, Italy',
            'BGY': 'Milan - Orio Al Serio, Italy',
            'MQL': 'Mildura, Australia',
            'MLS': 'Miles City (MT), USA',
            'MLT': 'Millinocket (ME), USA',
            'MKE': 'Milwaukee (WI), USA',
            'MTT': 'Minatitlan, Mexico',
            'MSP': 'Minneapolis - St. Paul International Airport (MN), USA',
            'MOT': 'Minot (ND), USA',
            'MSQ': 'Minsk, International, Belarus',
            'MHP': 'Minsk, Minsk International 1, Belarus',
            'MYY': 'Miri, Malaysia',
            'MSJ': 'Misawa, Japan',
            'MCQ': 'Miskolc, Hungary',
            'MSO': 'Missula (MT), USA',
            'MHE': 'Mitchell (SD), USA',
            'MJK': 'Monkey Mia, Australia',
            'MBT': 'Masbate, Philippines',
            'MOG': 'Mong Hsat, Myanmar',
            'MLI': 'Moline/Quad Cities (IL), USA',
            'MBA': 'Mombasa - Moi International, Kenya',
            'MIR': 'Monastir, Tunisia',
            'MBE': 'Monbetsu, Japan',
            'LOV': 'Monclova, Mexico',
            'YQM': 'Moncton, Canada',
            'MLU': 'Monroe (LA), USA',
            'ROB': 'Monrovia - Roberts International, Liberia',
            'MLW': 'Monrovia - Spriggs Payne, Liberia',
            'MBJ': 'Montego Bay - Sangster International, Jamaica',
            'MRY': 'Monterey (CA), USA',
            'MVD': 'Montevideo - Carrasco, Uruguay',
            'MGM': 'Montgomery (AL) - Montgomery Regional Airport, USA',
            'MPL': 'Montpellier - Méditerranée, France',
            'YMQ': 'Montreal, Canada',
            'YUL': 'Montreal - Dorval (Montréal-Trudeau), Canada',
            'YHU': 'Montreal - St. Hubert, Canada',
            'MTJ': 'Montrose/Telluride (CO), USA',
            'MOZ': 'Moorea, French Polynesia',
            'MOV': 'Moranbah, Australia',
            'MRZ': 'Moree, Australia',
            'MLM': 'Morelia, Mexico',
            'MGW': 'Morgantown (WV), USA',
            'HNA': 'Morioka, Japan',
            'HAH': 'Moroni - Prince Said Ibrahim, Comoros (Comores)',
            'MYA': 'Moruya, Australia',
            'MOW': 'Moscow, Russia',
            'DME': 'Moscow - Domodedovo, Russia',
            'SVO': 'Moscow - Sheremetyevo, Russia',
            'VKO': 'Moscow - Vnukovo, Russia',
            'MWH': 'Moses Lake (WA), USA',
            'MDE': 'Medellín - José María Córdova, Colombia',
            'MJK': 'Monkey Mia, Australia',
            'MLE': 'Male - International Airport, Maldives',
            'MSZ': 'Moçâmedes, Angola',
            'MGB': 'Mount Gambier, Australia',
            'MHU': 'Mount Hotham, Australia',
            'MCL': 'Mount McKinley (AK), USA',
            'MSY': 'New Orleans, La, USA',
            'MUC': 'Munich - Franz Josef Strauss, Germany',
            'MJV': 'Murcia, Spain',
            'MMK': 'Murmansk, Russia',
            'MSR': 'Mus, Turkey',
            'MCT': 'Muscat - Seeb, Oman',
            'MSL': 'Muscle Shoals (AL), USA',
            'MKG': 'Muskegon (MI), USA',
            'MFG': 'Muzaffarabad, Pakistan',
            'MVB': 'Mvengue, Gabon',
            'MYR': 'Myrtle Beach (SC) - Myrtle Beach International, USA',
            'MJT': 'Mytilene (Lesbos), Greece',
            'NDJ': 'N\'Djamena, Chad',
            'NAN': 'Nadi, Fiji',
            'NGS': 'Nagasaki, Japan',
            'NGO': 'Nagoya - Komaki AFB, Japan',
            'NAG': 'Nagpur, India',
            'NBO': 'Nairobi - Jomo Kenyatta International, Kenya',
            'WIL': 'Nairobi - Wilson, Kenya',
            'NAJ': 'Nakhichevan, Azerbaijan',
            'NST': 'Nakhon Si Thammarat, Thailand',
            'NLA': 'Ndola, Zambia',
            'NEC': 'Necochea, Argentina',
            'EAM': 'Nejran, Saudi Arabia',
            'NPL': 'New Plymouth, New Zealand',
            'NQY': 'Newquay, United Kingdom',
            'NGE': 'N\'Gaoundéré, Cameroon',
            'IAG': 'Niagara Falls International, USA',
            'NIM': 'Niamey, Niger',
            'NCE': 'Nice - Côte D\'Azur Airport, France',
            'NIC': 'Nicosia, Cyprus',
            'NLV': 'Nikolaev, Ukraine',
            'KIJ': 'Niigata, Japan',
            'FNI': 'Nimes, France',
            'INI': 'Nis, Serbia',
            'NGB': 'Ningbo, China',
            'NIX': 'Nioro, Mali',
            'NFO': 'Niuafo\'ou, Tonga',
            'NTT': 'Niuatoputapu, Tonga',
            'IUE': 'Niue Island, Niue',
            'NJC': 'Nizhnevartovsk, Russia',
            'GOJ': 'Nizhny Novgorod, Russia',
            'NOU': 'Noumea, New Caledonia',
            'NKC': 'Nouakchott, Mauritania',
            'OVB': 'Novosibirsk - Tolmachevo, Russia',
            'NUX': 'Novy Urengoy, Russia',
            'NUE': 'Nürnberg (Nuremberg), Germany',
            'OAK': 'Oakland (CA), USA',
            'OAX': 'Oaxaca - Xoxocotlan, Mexico',
            'ODS': 'Odessa, Ukraine',
            'ORB': 'Oerebro, Sweden',
            'OHD': 'Ohrid, Macedonia',
            'OIT': 'Oita, Japan',
            'OKJ': 'Okayama, Japan',
            'OKA': 'Okinawa, Ryukyo Island - Naha, Japan',
            'OKC': 'Oklahoma City (OK) - Will Rogers World, USA',
            'OLB': 'Olbia, Italy',
            'OLP': 'Olympic Dam, Australia',
            'OMA': 'Omaha (NE), USA',
            'OND': 'Ondangwa, Namibia',
            'ONT': 'Ontario (CA), USA',
            'ORN': 'Oran (Ouahran), Algeria',
            'OAG': 'Orange, Australia',
            'SNA': 'Orange County (Santa Ana) (CA), USA',
            'OMD': 'Oranjemund, Namibia',
            'ORB': 'Orebro, Sweden',
            'ORF': 'Norfolk/Virginia Beach (VA), USA',
            'OER': 'Ornskoldsvik, Sweden',
            'OSW': 'Orsk, Russia',
            'ITM': 'Osaka - Itami, Japan',
            'KIX': 'Osaka - Kansai International Airport, Japan',
            'OSA': 'Osaka, Metropolitan Area, Japan',
            'OSH': 'Oshkosh (WI), USA',
            'OSI': 'Osijek, Croatia (Hrvatska)',
            'OSL': 'Oslo - Oslo Airport, Gardermoen, Norway',
            'FBU': 'Oslo - Fornebu, Norway',
            'TRF': 'Oslo - Sandefjord, Norway',
            'YOW': 'Ottawa - Hull, Canada',
            'ODA': 'Ouadda, Central African Republic',
            'OZZ': 'Ouarzazate, Morocco',
            'OUA': 'Ouagadougou, Burkina Faso',
            'OUD': 'Oujda, Morocco',
            'OUL': 'Oulu, Finland',
            'OUH': 'Oudtshoorn, South Africa',
            'VPS': 'Valparaiso (FL), USA',
            'PAD': 'Paderborn/Lippstadt, Germany',
            'PAH': 'Paducah (KY), USA',
            'PGA': 'Page/Lake Powell (AZ), USA',
            'PPG': 'Pago Pago, American Samoa',
            'PKB': 'Pakersburg (WV) /Marietta (OH), USA',
            'PMO': 'Palermo - Punta Raisi, Italy',
            'PMI': 'Palma de Mallorca, Spain',
            'PMW': 'Palmas, Brazil',
            'PMR': 'Palmerston North, New Zealand',
            'PSP': 'Palm Springs (CA), USA',
            'PTY': 'Panama City - Tocumen International, Panama',
            'PFN': 'Panama City (FL), USA',
            'PJG': 'Panjgur, Pakistan',
            'PNL': 'Pantelleria, Italy',
            'PPT': 'Papeete - Faaa, French Polynesia (Tahiti)',
            'PFO': 'Paphos, Cyprus',
            'PBO': 'Paraburdoo, Australia',
            'PBM': 'Paramaribo - Zanderij International, Suriname',
            'PAR': 'Paris, France',
            'CDG': 'Paris - Charles de Gaulle, France',
            'ORY': 'Paris - Orly, France',
            'BVA': 'Paris - Beauvais, France',
            'PKB': 'Parkersburg (WV) /Marietta (OH), USA',
            'PKE': 'Parkes, Australia',
            'PSC': 'Pasco (WA), USA',
            'PSI': 'Pasni, Pakistan',
            'PAT': 'Patna, India',
            'PYX': 'Pattaya, Thailand',
            'PUF': 'Pau, France',
            'PLN': 'Pellston (MI), USA',
            'PEN': 'Penang International, Malaysia',
            'PDT': 'Pendelton (OR), USA',
            'PNS': 'Pensacola (FL), USA',
            'PIA': 'Peoria/Bloomington (IL), USA',
            'PEI': 'Pereira, Colombia',
            'PGF': 'Perpignan, France',
            'PER': 'Perth International, Australia',
            'PEG': 'Perugia, Italy',
            'PSR': 'Pescara, Italy',
            'PEW': 'Peshawar, Pakistan',
            'PKU': 'Pekanbaru, Indonesia',
            'PHL': 'Philadelphia (PA) - International, USA',
            'PNH': 'Phnom Penh - Pochentong, Cambodia',
            'PHX': 'Phoenix (AZ) - Sky Harbor International, USA',
            'HKT': 'Phuket, Thailand',
            'PIR': 'Pierre (SD), USA',
            'PZB': 'Pietermaritzburg, South Africa',
            'PTG': 'Pietersburg, South Africa',
            'PIT': 'Pittsburgh International Airport (PA), USA',
            'PLJ': 'Placencia, Belize',
            'PIH': 'Pocatello (ID), USA',
            'TGD': 'Podgorica, Montenegro',
            'PNI': 'Pohnpei, Micronesia',
            'PTP': 'Pointe a Pitre, Guadeloupe',
            'PIS': 'Poitiers - Biard, France',
            'PSE': 'Ponce, Puerto Rico',
            'PDL': 'Ponta Delgada, Portugal',
            'POR': 'Pori, Finland',
            'CLM': 'Port Angeles (WA), USA',
            'PAP': 'Port au Prince, Haiti',
            'PUG': 'Port Augusta, Australia',
            'WPB': 'Port Berge, Madagascar',
            'PLZ': 'Port Elizabeth, South Africa',
            'POG': 'Port Gentil, Gabon',
            'PHC': 'Port Harcourt, Nigeria',
            'PHE': 'Port Hedland, Australia',
            'PLO': 'Port Lincoln, Australia',
            'PQQ': 'Port Macquarie, Australia',
            'YPN': 'Port Meiner, Canada',
            'POM': 'Port Moresby - Jackson Field, Papua New Guinea',
            'OPO': 'Porto, Portugal',
            'POA': 'Porto Alegre - Salgado Filho International Airport, Brazil',
            'POS': 'Port of Spain - Piarco International, Trinidad and Tobago',
            'POU': 'Poughkeepsie (NY), USA',
            'POZ': 'Poznan, Poland',
            'PRG': 'Prague - Václav Havel Airport (formerly Ruzyne), Czech Republic',
            'RAI': 'Praia - Nelson Mandela International Airport, Cape Verde',
            'PQI': 'Presque Island (ME), USA',
            'PRY': 'Pretoria - Wonderboom Apt., South Africa',
            'PVK': 'Preveza/Lefkas, Greece',
            'YXS': 'Prince George, Canada',
            'YPR': 'Prince Rupert/Digby Island, Canada',
            'PRN': 'Pristina, Kosovo',
            'PPP': 'Prosperpine, Australia',
            'PVD': 'Providence (RI), USA',
            'SCC': 'Prudhoe Bay (AK), USA',
            'PBC': 'Puebla, Mexico',
            'PUB': 'Pueblo (CO), USA',
            'PUW': 'Pullman (WA), USA',
            'PNQ': 'Pune, India',
            'PUY': 'Pula, Croatia (Hrvatska)',
            'PUQ': 'Punta Arenas - Presidente Carlos Ibáñez del Campo, Chile',
            'PUJ': 'Punta Cana - Punta Cana International, Dominican Republic',
            'PUS': 'Pusan (Busan) - Gimhae International Airport, South Korea',
            'TPE': 'Taipei - Chiang Kai Shek, Taiwan',
            'TAY': 'Taipei - Sung Shan, Taiwan',
            'KHH': 'Kaohsiung International, Taiwan',
            'RMQ': 'Taichung, Taiwan',
            'TNN': 'Tainan, Taiwan',
            'TTT': 'Taitung, Taiwan',
            'TYN': 'Taiyuan, China',
            'TAK': 'Takamatsu, Japan',
            'TLL': 'Tallinn - Ulemiste International, Estonia',
            'TPE': 'Taipei - Chiang Kai Shek, Taiwan',
            'TAM': 'Tampico - Gen. F. Javier Mina, Mexico',
            'TNG': 'Tangier - Boukhalef, Morocco',
            'TRO': 'Taree, Australia',
            'TGV': 'Targovishte, Bulgaria',
            'TAS': 'Tashkent - International, Uzbekistan',
            'TWU': 'Tawau, Malaysia',
            'TBS': 'Tbilisi - Novo Alexeyevka, Georgia',
            'MME': 'Teesside, United Kingdom',
            'TEF': 'Telfer, Australia',
            'TLV': 'Tel Aviv - Ben Gurion International, Israel',
            'TIA': 'Tirana - Rinas, Albania',
            'TAB': 'Tobago, Trinidad and Tobago',
            'TKS': 'Tokushima, Japan',
            'TYO': 'Tokyo, Japan',
            'NRT': 'Tokyo - Narita, Japan',
            'HND': 'Tokyo - Haneda, Japan',
            'TOL': 'Toledo (OH), USA',
            'TPR': 'Tom Price, Australia',
            'TWB': 'Toowoomba, Australia',
            'YTZ': 'Toronto - Billy Bishop Toronto City Airport, Canada',
            'YYZ': 'Toronto - Lester B. Pearson International Airport, Canada',
            'YTO': 'Toronto, Canada',
            'TRC': 'Torreon, Mexico',
            'TTJ': 'Tottori, Japan',
            'TLN': 'Toulon, France',
            'TLS': 'Toulouse - Blagnac Airport, France',
            'TSV': 'Townsville, Australia',
            'TOY': 'Toyama, Japan',
            'TZX': 'Trabzon, Turkey',
            'TST': 'Trang, Thailand',
            'TDX': 'Trat, Thailand',
            'TVC': 'Traverse City (MI), USA',
            'TCB': 'Treasure Cay, Bahamas',
            'TTN': 'Trenton/Princeton (NJ), USA',
            'TSF': 'Treviso, Italy',
            'TRI': 'Tri-Cities Regional (TN) /VA, USA',
            'TRS': 'Trieste, Italy',
            'TIP': 'Tripoli - Tripoli International, Libya',
            'TOS': 'Tromso, Norway',
            'TRD': 'Trondheim, Norway',
            'TSN': 'Tianjin, China',
            'TKK': 'Truk, Micronesia',
            'TUS': 'Tucson (AZ), USA',
            'TUL': 'Tulsa (OK), USA',
            'TUN': 'Tunis - Carthage, Tunisia',
            'TUP': 'Tupelo (MS), USA',
            'TRN': 'Turin, Italy',
            'TKU': 'Turku, Finland',
            'TCL': 'Tuscaloosa (AL), USA',
            'TWF': 'Twin Falls (ID), USA',
            'TYR': 'Tyler (TX), USA',
            'UAH': 'Ua Huka, French Polynesia',
            'UAP': 'Ua Pou, French Polynesia',
            'UBJ': 'Ube, Japan',
            'UBA': 'Uberaba, Brazil',
            'UDI': 'Uberlandia, Brazil',
            'UCT': 'Ukhta, Russia',
            'ULN': 'Ulaanbaatar - Buyant Uhaa, Mongolia',
            'UUD': 'Ulan-Ude, Russia',
            'HLH': 'Ulanhot, China',
            'ULY': 'Ulyanovsk - Baratayevka, Russia',
            'UME': 'Umea, Sweden',
            'YUD': 'Umiujaq, Canada',
            'UTN': 'Upington, South Africa',
            'UGC': 'Urgench, Uzbekistan',
            'URC': 'Urumqi, China',
            'USH': 'Ushuaia - Islas Malvinas, Argentina',
            'UKK': 'Ust-Kamenogorsk, Kazakhstan',
            'UTP': 'Utapao (Pattaya), Thailand',
            'UCA': 'Utica (NY) - Oneida County Airport, USA',
            'UIO': 'Quito - Mariscal Sucre International Airport, Ecuador',
            'VAA': 'Vaasa, Finland',
            'VLR': 'Vallenar, Chile',
            'VLC': 'Valencia, Spain',
            'VLN': 'Valencia, Venezuela',
            'VLL': 'Valladolid, Spain',
            'VAP': 'Valparaiso, Chile',
            'VDE': 'Valverde, Spain',
            'VAN': 'Van - Ferit Melen, Turkey',
            'YVR': 'Vancouver - Vancouver International, Canada',
            'VRA': 'Varadero, Cuba',
            'VNS': 'Varanasi, India',
            'VRK': 'Varkaus, Finland',
            'VAR': 'Varna, Bulgaria',
            'VST': 'Vasteras, Sweden',
            'VLU': 'Velikiye Luki (Welikije Luki), Russia',
            'VCE': 'Venice - Marco Polo, Italy',
            'VER': 'Veracruz, Mexico',
            'VRN': 'Verona, Italy',
            'VYD': 'Vryheid, South Africa',
            'VIE': 'Vienna - Vienna International, Austria',
            'VTE': 'Vientiane - Wattay, Laos',
            'VQS': 'Vieques, Puerto Rico',
            'VGO': 'Vigo, Spain',
            'VSA': 'Villahermosa, Mexico',
            'VNO': 'Vilnius, Lithuania',
            'VIS': 'Visalia (CA), USA',
            'VBY': 'Visby, Sweden',
            'VIX': 'Vitoria, Brazil',
            'VIT': 'Vitoria, Spain',
            'VVO': 'Vladivostok, Russia',
            'VOG': 'Volgograd, Russia',
            'YWK': 'Wabush, Canada',
            'ACT': 'Waco (TX), USA',
            'WGA': 'Wagga, Australia',
            'ALW': 'Walla Walla (WA), USA',
            'WLS': 'Wallis, Wallis and Futuna Islands',
            'WVB': 'Walvis Bay, South Africa',
            'WMB': 'Warrnambool, Australia',
            'WAW': 'Warsaw - Frédéric Chopin, Poland',
            'BWI': 'Washington DC - Baltimore Washington International, USA',
            'DCA': 'Washington DC - Ronald Reagan National, USA',
            'IAD': 'Washington DC - Washington Dulles International, USA',
            'WAS': 'Washington, DC, USA',
            'ALO': 'Waterloo IA, USA',
            'ATY': 'Watertown (SD), USA',
            'CWA': 'Wausau/Stevens Point (WI), USA',
            'WEI': 'Weipa, Australia',
            'WEL': 'Welkom, South Africa',
            'WLG': 'Wellington, New Zealand',
            'EAT': 'Wenatchee (WA), USA',
            'PBI': 'West Palm Beach (FL), USA',
            'WYS': 'West Yellowstone (MT), USA',
            'WHK': 'Whakatane, New Zealand',
            'WRE': 'Whangarei, New Zealand',
            'HPN': 'White Plains (NY), USA',
            'YXY': 'Whitehorse, Canada',
            'WIC': 'Wick, United Kingdom',
            'WHM': 'Wickham, Australia',
            'SPS': 'Wichita Falls (TX), USA',
            'ICT': 'Wichita (KS), USA',
            'WIE': 'Wiesbaden, Germany',
            'AVP': 'Wilkes Barre/Scranton (PA), USA',
            'IPT': 'Williamsport (PA), USA',
            'ISL': 'Williston (ND), USA',
            'ILM': 'Wilmington (NC), USA',
            'VNO': 'Vilnius, Lithuania',
            'WUN': 'Wiluna, Australia',
            'WNR': 'Windorah, Australia',
            'YQG': 'Windsor Ontario, Canada',
            'YWG': 'Winnipeg International, Canada',
            'INT': 'Winston Salem (NC), USA',
            'OLF': 'Wolf Point (MT), USA',
            'WOL': 'Wollongong, Australia',
            'UMR': 'Woomera, Australia',
            'ORH': 'Worcester (MA), USA',
            'WRL': 'Worland (WY), USA',
            'WRG': 'Wrangell (AK), USA',
            'WUH': 'Wuhan, China',
            'WYN': 'Wyndham, Australia',
            'XMN': 'Xiamen, China',
            'XIY': 'Xi\'an - Xianyang, China',
            'YKM': 'Yakima (WA), USA',
            'YAK': 'Yakutat (AK), USA',
            'YNB': 'Yanbu, Saudi Arabia',
            'RGN': 'Yangon (Rangoon) - Mingaladon, Myanmar',
            'YNY': 'Yangyang, South Korea',
            'YAP': 'Yap, Micronesia',
            'YZF': 'Yellowknife, Canada',
            'YEO': 'Yeovil, United Kingdom',
            'YIH': 'Yichang, China',
            'YOK': 'Yokohama, Japan',
            'YUM': 'Yuma (AZ), USA',
            'ZCL': 'Zacatecas, Mexico',
            'ZAD': 'Zadar, Croatia (Hrvatska)',
            'ZAG': 'Zagreb - Pleso, Croatia (Hrvatska)',
            'ZTH': 'Zakynthos, Greece',
            'ZAZ': 'Zaragoza, Spain',
            'ZHA': 'Zhanjiang, China',
            'ZQZ': 'Zhangjiakou, China',
            'ZAT': 'Zhaotong, China',
            'CGO': 'Zhengzhou, China',
            'PZH': 'Zhob, Pakistan',
            'ZIG': 'Ziguinchor, Senegal',
            'ILZ': 'Zilina, Slovakia',
            'ZIH': 'Zihuatanejo/Ixtapa, Mexico',
            'ZNZ': 'Zanzibar - Kisauni, Tanzania',
            'ZRH': 'Zurich (Zürich) - Kloten, Switzerland',
            'LHR': 'London - Heathrow, UK',
            'LGW': 'London - Gatwick, UK',
            'STN': 'London - Stansted, UK',
            'LTN': 'London - Luton, UK',
            'LCY': 'London - City, UK',
            'MAN': 'Manchester, UK',
            'EDI': 'Edinburgh, UK',
            'GLA': 'Glasgow, UK',
            'BHX': 'Birmingham, UK',
            'BRS': 'Bristol, UK',
            'NCL': 'Newcastle, UK',
            'ABZ': 'Aberdeen, UK',
            'INV': 'Inverness, UK',
            'JFK': 'New York - John F. Kennedy, USA',
            'EWR': 'Newark, USA',
            'LGA': 'New York - LaGuardia, USA',
            'SFO': 'San Francisco, USA',
            'SEA': 'Seattle, USA',
            'PDX': 'Portland, USA',
            'SJC': 'San Jose, USA',
            'OAK': 'Oakland, USA',
            'LAX': 'Los Angeles, USA',
            'SAN': 'San Diego, USA',
            'LAS': 'Las Vegas, USA',
            'PHX': 'Phoenix, USA',
            'DEN': 'Denver, USA',
            'DFW': 'Dallas/Fort Worth, USA',
            'IAH': 'Houston, USA',
            'ATL': 'Atlanta, USA',
            'ORD': 'Chicago - O\'Hare, USA',
            'MDW': 'Chicago - Midway, USA',
            'MIA': 'Miami, USA',
            'FLL': 'Fort Lauderdale, USA',
            'TPA': 'Tampa, USA',
            'MCO': 'Orlando, USA',
            'JAX': 'Jacksonville, USA',
            'PBI': 'West Palm Beach, USA',
            'MSY': 'New Orleans, USA',
            'BNA': 'Nashville, USA',
            'CLT': 'Charlotte, USA',
            'PHL': 'Philadelphia, USA',
            'BWI': 'Baltimore-Washington, USA',
            'DCA': 'Washington - Reagan, USA',
            'IAD': 'Washington - Dulles, USA',
            'BOS': 'Boston, USA',
            'PVD': 'Providence, USA',
            'BDL': 'Hartford, USA',
            'ALB': 'Albany, USA',
            'BUF': 'Buffalo, USA',
            'ROC': 'Rochester, USA',
            'SYR': 'Syracuse, USA',
            'AVP': 'Scranton, USA',
            'ISP': 'Islip, USA',
            'HPN': 'White Plains, USA',
            'PWM': 'Portland, USA',
            'PQI': 'Presque Isle, USA',
            'AUG': 'Augusta, USA',
            'BGR': 'Bangor, USA',
            'BTV': 'Burlington, USA',
            'MHT': 'Manchester, USA',
            'PIT': 'Pittsburgh, USA',
            'CLE': 'Cleveland, USA',
            'DTW': 'Detroit, USA',
            'GRR': 'Grand Rapids, USA',
            'LAN': 'Lansing, USA',
            'FNT': 'Flint, USA',
            'AZO': 'Kalamazoo, USA',
            'BTL': 'Battle Creek, USA',
            'CIU': 'Chippewa County, USA',
            'MQT': 'Marquette, USA',
            'IRN': 'Ironwood, USA',
            'CMX': 'Hancock, USA',
            'DLH': 'Duluth, USA',
            'RST': 'Rochester, USA',
            'LSE': 'La Crosse, USA',
            'CRL': 'Central Wisconsin, USA',
            'ATW': 'Appleton, USA',
            'GRB': 'Green Bay, USA',
            'MKE': 'Milwaukee, USA',
            'MSN': 'Madison, USA',
            'EAU': 'Eau Claire, USA',
            'LMT': 'Klamath Falls, USA',
            'MFR': 'Medford, USA',
            'EUG': 'Eugene, USA',
            'PDX': 'Portland, USA',
            'BLI': 'Bellingham, USA',
            'SEA': 'Seattle, USA',
            'GEG': 'Spokane, USA',
            'PSC': 'Pasco, USA',
            'ALW': 'Walla Walla, USA',
            'PDT': 'Pendleton, USA',
            'BOI': 'Boise, USA',
            'SUN': 'Sun Valley, USA',
            'JAC': 'Jackson Hole, USA',
            'GUC': 'Gunnison, USA',
            'MTJ': 'Telluride, USA',
            'ASE': 'Aspen, USA',
            'EGE': 'Vail, USA',
            'HDN': 'Hayden, USA',
            'GJT': 'Grand Junction, USA',
            'PUB': 'Pueblo, USA',
            'COS': 'Colorado Springs, USA',
            'DEN': 'Denver, USA',
            'APA': 'Centennial, USA',
            'BJC': 'Rocky Mountain, USA',
            'FNL': 'Fort Collins, USA',
            'GXY': 'Greeley, USA',
            'LAA': 'Laramie, USA',
            'CPR': 'Casper, USA',
            'CYS': 'Cheyenne, USA',
            'BIL': 'Billings, USA',
            'BZN': 'Bozeman, USA',
            'GTF': 'Great Falls, USA',
            'GEG': 'Spokane, USA',
            'MSO': 'Missoula, USA',
            'HLN': 'Helena, USA',
            'BIL': 'Billings, USA',
            'ISN': 'Williston, USA',
            'MOT': 'Minot, USA',
            'BIS': 'Bismarck, USA',
            'FCA': 'Kalispell, USA',
            'GTF': 'Great Falls, USA',
            'HLN': 'Helena, USA',
            'MSO': 'Missoula, USA',
            'BZN': 'Bozeman, USA',
            'JAC': 'Jackson Hole, USA',
            'COD': 'Cody, USA',
            'PNA': 'Pinedale, USA',
            'RKS': 'Rock Springs, USA',
            'SHR': 'Sheridan, USA',
            'WRL': 'Worland, USA',
            'BPI': 'Big Piney, USA',
            'CPK': 'Cookeville, USA',
            'TRI': 'Tri-Cities, USA',
            'CHA': 'Chattanooga, USA',
            'BNA': 'Nashville, USA',
            'SDF': 'Louisville, USA',
            'CVG': 'Cincinnati, USA',
            'LUK': 'Cincinnati Municipal, USA',
            'CMH': 'Columbus, USA',
            'LCK': 'Columbus Rickenbacker, USA',
            'TOL': 'Toledo, USA',
            'MBS': 'Saginaw, USA',
            'FNT': 'Flint, USA',
            'LAN': 'Lansing, USA',
            'AZO': 'Kalamazoo, USA',
            'BTL': 'Battle Creek, USA',
            'CIU': 'Chippewa County, USA',
            'MQT': 'Marquette, USA',
            'IRN': 'Ironwood, USA',
            'CMX': 'Hancock, USA',
            'DLH': 'Duluth, USA',
            'RST': 'Rochester, USA',
            'LSE': 'La Crosse, USA',
            'CRL': 'Central Wisconsin, USA',
            'ATW': 'Appleton, USA',
            'GRB': 'Green Bay, USA',
            'MKE': 'Milwaukee, USA',
            'MSN': 'Madison, USA',
            'EAU': 'Eau Claire, USA',
            'EAU': 'Eau Claire, USA'
        };
        let AIRLINES = {
            'AA': 'American Airlines',
            'AC': 'Air Canada',
            'AF': 'Air France',
            'AH': 'Air Algerie',
            'AI': 'Air India',
            'AL': 'Aerolineas Argentinas',
            'AM': 'Aeromexico',
            'AR': 'Aerolineas Argentinas',
            'AS': 'Alaska Airlines',
            'AT': 'Royal Air Maroc',
            'AV': 'Avianca',
            'AZ': 'Alitalia',
            'BA': 'British Airways',
            'BR': 'EVA Air',
            'CA': 'Air China',
            'CI': 'China Airlines',
            'CX': 'Cathay Pacific',
            'DL': 'Delta Air Lines',
            'EK': 'Emirates',
            'ET': 'Ethiopian Airlines',
            'EY': 'Etihad Airways',
            'FI': 'Icelandair',
            'FR': 'Ryanair',
            'GA': 'Garuda Indonesia',
            'IB': 'Iberia',
            'JL': 'Japan Airlines',
            'KL': 'KLM',
            'LA': 'LAN Airlines',
            'LH': 'Lufthansa',
            'LX': 'Swiss International Air Lines',
            'MH': 'Malaysia Airlines',
            'MS': 'Egyptair',
            'NH': 'All Nippon Airways',
            'NZ': 'Air New Zealand',
            'QF': 'Qantas',
            'QR': 'Qatar Airways',
            'SK': 'SAS',
            'SQ': 'Singapore Airlines',
            'SU': 'Aeroflot',
            'TK': 'Turkish Airlines',
            'UA': 'United Airlines',
            'UL': 'SriLankan Airlines',
            'VS': 'Virgin Atlantic',
            'VX': 'Virgin America',
            'WN': 'Southwest Airlines',
            'WS': 'WestJet',
            'ZZ': 'Other',
            'A3': 'Aegean Airlines',
            'A9': 'Air Iceland',
            'AB': 'Air Berlin',
            'AE': 'Mandala Airlines',
            'AY': 'Finnair',
            'AZ': 'Alitalia',
            'B6': 'JetBlue Airways',
            'B7': 'Air Berlin',
            'BG': 'Biman Bangladesh Airlines',
            'BI': 'Royal Brunei Airlines',
            'BT': 'Air Baltic',
            'CM': 'Copa Airlines',
            'CZ': 'China Southern Airlines',
            'DA': 'Air Denmark',
            'DY': 'Norwegian Air Shuttle',
            'EE': 'Aer Lingus',
            'F9': 'Frontier Airlines',
            'FB': 'Bulgaria Air',
            'G3': 'Gol Transportes Aéreos',
            'GF': 'Gulf Air',
            'GJ': 'Jetstar Asia Airways',
            'HM': 'Air Seychelles',
            'HO': 'Juneyao Airlines',
            'HU': 'Hainan Airlines',
            'HX': 'Hong Kong Airlines',
            'HY': 'Uzbekistan Airways',
            'IC': 'Indian Airlines',
            'JJ': 'LATAM Airlines Brasil',
            'JP': 'Adria Airways',
            'JU': 'Jat Airways',
            'KF': 'Kuwit Airways',
            'LG': 'Luxair',
            'LO': 'LOT Polish Airlines',
            'LP': 'LAN Peru',
            'LX': 'Swiss International Air Lines',
            'LY': 'El Al Israel Airlines',
            'MF': 'Xiamen Airlines',
            'MU': 'China Eastern Airlines',
            'N4': 'Air Vanuatu',
            'NX': 'Air Macau',
            'O6': 'Solomon Airlines',
            'OU': 'Croatia Airlines',
            'PK': 'Pakistan International Airlines',
            'PX': 'Air Niugini',
            'RJ': 'Royal Jordanian',
            'SN': 'Brussels Airlines',
            'SV': 'Saudia',
            'S7': 'S7 Airlines',
            'TO': 'Germania',
            'TR': 'Tigerair',
            'TS': 'Air Transat',
            'U2': 'easyJet',
            'UJ': 'Hageland Aviation',
            'UO': 'HK Express',
            'UT': 'Air Ukraine',
            'V3': 'TNT Airways',
            'V7': 'Volotea',
            'V8': 'Ittia Airlines',
            'VY': 'Vueling Airlines',
            'W6': 'Wizz Air',
            'Y4': 'Volaris',
            'YO': 'Helvetic Airways',
            'ZE': 'Flybe'
        };
